# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-08 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Women',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('dob', models.DateField(auto_now=True)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
                ('background', models.CharField(blank=True, max_length=10, null=True)),
                ('time_of_stay', models.IntegerField(blank=True, max_length=10, null=True)),
                ('skills', models.CharField(blank=True, max_length=20, null=True)),
                ('trainings', models.CharField(blank=True, max_length=20, null=True)),
                ('level_of_skill', models.IntegerField(blank=True, max_length=5, null=True)),
                ('cur_salary', models.IntegerField()),
                ('cur_location', models.CharField(blank=True, max_length=30, null=True)),
                ('future_plans', models.TextField(blank=True, max_length=30, null=True)),
                ('remarks', models.TextField(blank=True, max_length=30, null=True)),
                ('date_of_survey', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
