# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-08 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kshamata_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='id',
            new_name='aadhar_id',
        ),
        migrations.AlterField(
            model_name='women',
            name='background',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='women',
            name='level_of_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='women',
            name='time_of_stay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
