# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-08 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kshamata_users', '0002_auto_20170708_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='cur_location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='women',
            name='cur_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='women',
            name='dob',
            field=models.DateField(default=datetime.datetime(2017, 7, 8, 10, 10, 44, 685851, tzinfo=utc)),
        ),
    ]
