# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-08 11:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kshamata_users', '0003_auto_20170708_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='dob',
            field=models.DateField(default=datetime.datetime(2017, 7, 8, 11, 0, 33, 217076, tzinfo=utc)),
        ),
    ]
