# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-08 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kshamata_users', '0004_auto_20170708_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('purpose', models.CharField(blank=True, max_length=30, null=True)),
                ('women_count', models.IntegerField()),
                ('response_shelter', models.TextField(blank=True, max_length=30, null=True)),
                ('respone_women', models.TextField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='women',
            name='dob',
            field=models.DateField(default=datetime.datetime(2017, 7, 8, 13, 46, 58, 182362, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='women',
            field=models.ManyToManyField(to='kshamata_users.Women'),
        ),
        migrations.AddField(
            model_name='activity',
            name='target',
            field=models.ManyToManyField(to='kshamata_users.Women'),
        ),
    ]
